#!/bin/bash

sudo apt install fish curl -y

curl -sS https://starship.rs/install.sh | sh

# Config file
mkdir -p ~/.config/fish
rm ~/.config/fish/config.fish
ln -s ~/tools/shell/config.fish ~/.config/fish/config.fish


mkdir ~/apps/bin -p

export PATH="$HOME/apps/bin:$PATH"

chsh -s /usr/bin/fish
