#!/bin/bash

sudo apt install kitty

# Config file
mkdir ~/.config/kitty -p
rm -rf ~/.config/kitty/kitty.conf
ln -s ~/tools/kitty/kitty.conf ~/.config/kitty/kitty.conf

gsettings set org.gnome.desktop.default-applications.terminal exec '/usr/bin/kitty'
