#!/usr/bin/bash

mkdir -p ~/apps/bin
mkdir -p ~/tools/downloads
wget -P ~/tools/downloads https://github.com/jesseduffield/lazygit/releases/download/v0.44.1/lazygit_0.44.1_Linux_32-bit.tar.gz
tar -xzf ~/tools/downloads/lazygit_0.44.1_Linux_32-bit.tar.gz -C ~/tools/downloads/
cp ~/tools/downloads/lazygit ~/apps/bin/lg
rm ~/tools/downloads -rf

