vim.keymap.set({ "n", "t" }, "<A-h>", "<cmd>vertical resize -2<CR>", { silent = true, desc = "Decrease window width" })
vim.keymap.set({ "n", "t" }, "<A-l>", "<cmd>vertical resize +2<CR>", { silent = true, desc = "Increase window width" })
vim.keymap.set({ "n", "t" }, "<A-j>", "<cmd>resize -2<CR>", { silent = true, desc = "Decrease window height" })
vim.keymap.set({ "n", "t" }, "<A-k>", "<cmd>resize +2<CR>", { silent = true, desc = "Increase window height" })
vim.keymap.set({ "i", "n", "v", "c" }, "<leader><leader>", "<esc>", { silent = false, desc = "Nomal mode" })
vim.keymap.set({ "t" }, "<leader><leader>", "<c-\\><c-n>", { silent = true, desc = "Exit terminal mode" })
vim.keymap.set({ "n" }, "<leader>wo", "<c-w>o", { silent = true, desc = "Close others windows" })
vim.keymap.set({ "n" }, "<leader>wx", "<c-w>c", { silent = true, desc = "Close others windows" })
vim.keymap.set({ "n" }, "<leader>wv", "<c-w>v", { silent = true, desc = "Split window vertical" })
vim.keymap.set({ "n" }, "<leader>ws", "<c-w>s", { silent = true, desc = "Split window horizontal" })
vim.keymap.set({ "i", "n", "t" }, "<leader>wh", "<cmd>wincmd h<cr>", { silent = true, desc = "Go left" })
vim.keymap.set({ "i", "n", "t" }, "<leader>wj", "<cmd>wincmd j<cr>", { silent = true, desc = "Go down" })
vim.keymap.set({ "i", "n", "t" }, "<leader>wk", "<cmd>wincmd k<cr>", { silent = true, desc = "Go up" })
vim.keymap.set({ "i", "n", "t" }, "<leader>wl", "<cmd>wincmd l<cr>", { silent = true, desc = "Go right" })
vim.keymap.set({ "n", "i", "t" }, "<leader><S-q><S-q>", "<cmd>q!<CR>", { silent = true, desc = "Close window without save buffer" })
vim.keymap.set({ "n", "i", "t" }, "<leader><S-q><S-a>", "<cmd>qa!<CR>", { silent = true, desc = "Close all windows, without save buffers" })
vim.keymap.set({ "n", "i", "t" }, "<leader>qq", "<cmd>q<CR>", { silent = true, desc = "Close window" })
vim.keymap.set({ "n", "i", "t" }, "<leader>qa", "<cmd>qa<CR>", { silent = true, desc = "Close all windows" })
vim.keymap.set({ "n", "i" }, "<leader>ww", "<cmd>w<CR>", { silent = true, desc = "Write buffer" })
vim.keymap.set({ "n", "t" }, "<leader>wq", "<cmd>wq<CR>", { silent = true, desc = "Write buffer and quit" })
vim.keymap.set({ "n", "t" }, "<leader>wa", "<cmd>wa<CR>", { silent = true, desc = "Write all buffers" })
vim.keymap.set({ "v" }, "<leader>y", "\"+y", { silent = true, desc = "Yank to clipboard" })
vim.keymap.set({ "n", "v" }, "<leader>p", "\"+p", { silent = true, desc = "Paste from clipboard" })
vim.keymap.set({ "v" }, "<leader>[", "c[]<esc><s-p>", { silent = true, desc = "Sunround by brackets" })
vim.keymap.set({ "n" }, "<leader>[", "di[va[p", { silent = true, desc = "Remove brackets" })
vim.keymap.set({ "v" }, "<leader>(", "c()<esc><s-p>", { silent = true, desc = "Sunround by parentheses" })
vim.keymap.set({ "n" }, "<leader>(", "di(va(p", { silent = true, desc = "Remove parentheses" })
vim.keymap.set({ "v" }, "<leader>{", "c{}<esc><s-p>", { silent = true, desc = "Sunround by keys" })
vim.keymap.set({ "n" }, "<leader>{", "di{va{p", { silent = true, desc = "Remove keys" })
vim.keymap.set({ "v" }, "<leader>`", "c``<esc><s-p>", { silent = true, desc = "Sunround by crasis" })
vim.keymap.set({ "n" }, "<leader>`", "di`va`p", { silent = true, desc = "Remove crasis" })
vim.keymap.set({ "v" }, "<leader>'", "c''<esc><s-p>", { silent = true, desc = "Sunround by single quotes" })
vim.keymap.set({ "n" }, "<leader>'", "di'va'p", { silent = true, desc = "Remove single quotes" })
vim.keymap.set({ "v" }, "<leader>\"", "c\"\"<esc><s-p>", { silent = true, desc = "Sunround by quotes" })
vim.keymap.set({ "n" }, "<leader>\"", "di\"va\"p", { silent = true, desc = "Remove quotes" })
vim.keymap.set({ "n" }, "<leader>rr", "<cmd>source ~/.config/nvim/init.lua<cr>", { silent = true, desc = "Reload init.lua" })
vim.keymap.set({ "n" }, "<leader>co", "<cmd>e ~/.config/nvim/<cr>", { silent = true, desc = "Open configurations" })
