local keymap_set = vim.keymap.set

keymap_set({ "n" }, "<A-h>", "<cmd>vertical resize -2<CR>", { silent = true, desc = "Decrease window width" })
keymap_set({ "n" }, "<A-l>", "<cmd>vertical resize +2<CR>", { silent = true, desc = "Increase window width" })
keymap_set({ "n" }, "<A-j>", "<cmd>resize -2<CR>", { silent = true, desc = "Decrease window height" })
keymap_set({ "n" }, "<A-k>", "<cmd>resize +2<CR>", { silent = true, desc = "Increase window height" })
keymap_set({ "n", "i", "v", "c" }, "<leader><leader>", "<esc>", { silent = false, desc = "Nomal mode" })
keymap_set({ "t" }, "<leader><leader>", "<c-\\><c-n>", { silent = true, desc = "Exit terminal mode" })
keymap_set({ "n" }, "<leader>wo", "<c-w>o", { silent = true, desc = "Close others windows" })
keymap_set({ "n" }, "<leader>wx", "<c-w>c", { silent = true, desc = "Close current window" })
keymap_set({ "n" }, "<leader>wv", "<c-w>v", { silent = true, desc = "Split window vertical" })
keymap_set({ "n" }, "<leader>ws", "<c-w>s", { silent = true, desc = "Split window horizontal" })
keymap_set({ "n" }, "<leader>w_", "<cmd>wincmd _<cr>", { silent = true, desc = "Maximize vertical" })
keymap_set({ "n" }, "<leader>w|", "<cmd>wincmd |<cr>", { silent = true, desc = "Maximize vertical" })
keymap_set({ "n", "t" }, "<leader>wh", "<cmd>wincmd h<cr>", { silent = true, desc = "Go left" })
keymap_set({ "n", "t" }, "<leader>wj", "<cmd>wincmd j<cr>", { silent = true, desc = "Go down" })
keymap_set({ "n", "t" }, "<leader>wk", "<cmd>wincmd k<cr>", { silent = true, desc = "Go up" })
keymap_set({ "n", "t" }, "<leader>wl", "<cmd>wincmd l<cr>", { silent = true, desc = "Go right" })
keymap_set({ "n" }, "<leader>qq", "<cmd>q<CR>", { silent = true, desc = "Close window" })
keymap_set({ "n" }, "<leader>qa", "<cmd>qa<CR>", { silent = true, desc = "Close all windows" })
keymap_set({ "n" }, "<leader>ww", "<cmd>w<CR>", { silent = true, desc = "Write buffer" })
keymap_set({ "n" }, "<leader>wa", "<cmd>wa<CR>", { silent = true, desc = "Write all buffers" })
keymap_set({ "v" }, "<leader>y", "\"+y", { silent = true, desc = "Yank to clipboard" })
keymap_set({ "v", "n" }, "<leader>p", "\"+p", { silent = true, desc = "Paste from clipboard" })
keymap_set({ "v" }, "<leader>sb", "c[]<esc><s-p>", { silent = true, desc = "Sunround by brackets" })
keymap_set({ "n" }, "<leader>sb", "di[va[p", { silent = true, desc = "Remove brackets" })
keymap_set({ "v" }, "<leader>sp", "c()<esc><s-p>", { silent = true, desc = "Sunround by parentheses" })
keymap_set({ "n" }, "<leader>sp", "di(va(p", { silent = true, desc = "Remove parentheses" })
keymap_set({ "v" }, "<leader>sk", "c{}<esc><s-p>", { silent = true, desc = "Sunround by keys" })
keymap_set({ "n" }, "<leader>sk", "di{va{p", { silent = true, desc = "Remove keys" })
keymap_set({ "v" }, "<leader>sc", "c``<esc><s-p>", { silent = true, desc = "Sunround by crasis" })
keymap_set({ "n" }, "<leader>sc", "di`va`p", { silent = true, desc = "Remove crasis" })
keymap_set({ "v" }, "<leader>sQ", "c''<esc><s-p>", { silent = true, desc = "Sunround by single quotes" })
keymap_set({ "n" }, "<leader>sQ", "di'va'p", { silent = true, desc = "Remove single quotes" })
keymap_set({ "v" }, "<leader>sq", "c\"\"<esc><s-p>", { silent = true, desc = "Sunround by quotes" })
keymap_set({ "n" }, "<leader>sq", "di\"va\"p", { silent = true, desc = "Remove quotes" })
keymap_set({ "n" }, "<leader>diQ", "di\"", { silent = true, desc = "Delete inside quotes" })
keymap_set({ "n" }, "<leader>diq", "di'", { silent = true, desc = "Delete inside single quotes" })
keymap_set({ "n" }, "<leader>dik", "di{", { silent = true, desc = "Delete inside keys" })
keymap_set({ "n" }, "<leader>dib", "di[", { silent = true, desc = "Delete inside brackets" })
keymap_set({ "n" }, "<leader>dip", "di(", { silent = true, desc = "Delete inside params" })
keymap_set({ "n" }, "<leader>dic", "di`", { silent = true, desc = "Delete inside crasis" })
keymap_set({ "n" }, "<leader>daQ", "da\"", { silent = true, desc = "Delete including quotes" })
keymap_set({ "n" }, "<leader>daq", "da'", { silent = true, desc = "Delete including single quotes" })
keymap_set({ "n" }, "<leader>dak", "da{", { silent = true, desc = "Delete including keys" })
keymap_set({ "n" }, "<leader>dab", "da[", { silent = true, desc = "Delete including brackets" })
keymap_set({ "n" }, "<leader>dap", "da(", { silent = true, desc = "Delete including params" })
keymap_set({ "n" }, "<leader>dac", "da`", { silent = true, desc = "Delete including crasis" })
keymap_set({ "n" }, "<leader>so", "<cmd>source %<cr>", { silent = true, desc = "Source current file" })
