#!/bin/bash

mkdir ~/apps/bin -p
mkdir ~/tools/downloads -p

wget -O ~/tools/downloads/zellij.tar.gz https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz
tar -xzf ~/tools/downloads/zellij.tar.gz -C ~/tools/downloads
cp ~/tools/downloads/zellij ~/apps/bin
rm ~/tools/downloads -rf

# Configuration
mkdir ~/.config/zellij/ -p
rm ~/.config/zellij/config.kdl
ln -s ~/tools/zellij/config.kdl ~/.config/zellij/config.kdl
