#!/bin/bash

mkdir ~/apps/bin -p

wget -O ~/apps/zellij.tar.gz https://github.com/zellij-org/zellij/releases/latest/download/zellij-x86_64-unknown-linux-musl.tar.gz
tar -xzf ~/apps/zellij.tar.gz -C ~/apps/
rm ~/apps/zellij.tar.gz

ln -s ~/apps/zellij ~/apps/bin/zellij
