#!/usr/bin/bash

mkdir -p ~/apps/bin
mkdir -p ~/tools/downloads
wget -P ~/tools/downloads https://github.com/LucasPickering/slumber/releases/download/v2.5.0/slumber-x86_64-unknown-linux-gnu.tar.xz
tar -xJf ~/tools/downloads/slumber-x86_64-unknown-linux-gnu.tar.xz -C ~/tools/downloads/
cp ~/tools/downloads/slumber-x86_64-unknown-linux-gnu/slumber ~/apps/bin
rm ~/tools/downloads -rf

mkdir ~/.config/slumber -p
cp ~/tools/slumber/config.yml ~/.config/slumber
